# netlify.toml at project root

[build]
  base = "."                             
  publish = "client/dist"               
  functions = "netlify/functions"       # Your functions are here at root/netlify/functions
  command = "npm run build"             # Use root build script

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200


# Fallback redirect to serve index.html for client-side routing (React Router)
[[redirects]]
  from = "/{any*}"
  to = "/index.html"
  status = 200
  force = true
