# Netlify configuration file

[build]
  base = "client"                     # Tells Netlify to cd into the client folder
  publish = "build"                   # Inside 'client' after build runs
  functions = "../netlify/functions" # Relative to the 'client' base directory
  command = "npm run build"          # Will run inside the 'client' folder

# Redirects to route API requests to Netlify functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
