# netlify.toml at project root

[build]
  base = "."                             # Run everything from project root
  publish = "client/dist"               # Vite outputs to dist inside client
  functions = "netlify/functions"       # Your functions are here at root/netlify/functions
  command = "npm run build"             # Use root build script

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Fallback redirect for all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
